[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
mainnet  = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
arbitrum = "${RPC_ARBITRUM}"

[fmt]
line_length = 100

# Flare Networks for FAssets
coston = "https://coston-api.flare.network/ext/bc/C/rpc"
songbird = "https://songbird-api.flare.network/ext/bc/C/rpc" 
flare = "https://flare-api.flare.network/ext/bc/C/rpc"
