name: "Scheduled tests"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1' # 00:00 every monday

jobs:


  schedule-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install node modules
      run: yarn install --frozen-lockfile
    - name: Compile contracts
      run: yarn run compile
    - name: Run the test
      run: yarn run test-with-coverage


  schedule-fuzzer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_OPTIONS: "--max_old_space_size=6144"
      LOOPS: 5000
      CHANGE_PRICE_AT: '300,600,...'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install node modules
      run: yarn install --frozen-lockfile
    - name: Compile contracts
      run: yarn run compile
    - name: Run the test
      run: yarn run fasset_simulation
    - name: Archive fuzzer log
      uses: actions/upload-artifact@v4
      with:
        name: fuzzer-log
        path: test_logs/fasset-simulation.log
